### PR TITLE
Test to see changes in 2018C1 folder on CMSws2

### PR DESCRIPTION
**Pull request by kevinyager**
Test to compare codes from KY system and CMSws2

### CODE REVIEW

**Comment by kevinyager** [comment]
These changes were manually added to master. This pull is no longer needed.

**Comment by esther279** [comment]
@kevinyager 
- RL wants to add to the master a mask file (seen as the only file change), so you/me can merge this pull request.
- I did 'git pull origin master' at the beamline and it works (automatically merging files), see http://gisaxs.com/CS/index.php/Github#Beginning_of_beamtime 
- The repository is now on both ws2 and GPFS
Thanks for your patience, hope all will work smoothly from now on!

**Comment by kevinyager** [comment]
This was a test. It's been superseded by changes made in the master branch.

**Comment by kevinyager** [comment]
New mask file merged.

**Pull request merged**
